// omni-dev sessions feed for pi.dev — generated by `omni-dev sessions install-hooks`.
// Do not edit: `install-hooks` rewrites this file and `uninstall-hooks` deletes it.
//
// Reports this pi session's coarse state (working / idle / waiting_for_input)
// to the omni-dev daemon's `sessions` service, so pi sessions
// show up beside Claude Code ones in `omni-dev sessions list`, the tray and the
// VS Code worktrees tree (#1901). The state comes straight from pi's lifecycle
// events, so it is sent as an authoritative `stream_state` (ADR-0057).
//
// Fail-open by construction: no handler awaits the daemon, every error is
// swallowed, and a missing daemon costs one refused connect. Only state is
// sent — never a prompt, a message or a tool argument.

import { createConnection } from "node:net";

/** The daemon control socket, resolved when this file was generated. */
const SOCKET: string = __OMNI_DEV_SOCKET__;

/** Re-report the current state this often, so an idle session is not aged out. */
const KEEPALIVE_MS = 30_000;
/** Give up on one daemon round-trip after this long. */
const SEND_TIMEOUT_MS = 2_000;
/** Drop reports rather than queue without bound behind a wedged daemon. */
const MAX_PENDING = 32;
/** How long `session_shutdown` waits for queued reports before letting pi exit. */
const SHUTDOWN_FLUSH_MS = 1_500;

type State = "working" | "idle" | "waiting_for_input";

interface Session {
  id: string;
  cwd?: string;
  file?: string;
  model?: string;
}

// pi's extension types live in `@earendil-works/pi-coding-agent`; they are not
// imported so this file has no dependency to resolve. Only the members read
// below are relied on, and each read is guarded.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Any = any;

export default function (pi: Any): void {
  let session: Session | undefined;
  let state: State = "idle";
  // Between `agent_start` and `agent_settled`, so a closed UI prompt knows
  // whether to return to `working` or `idle`.
  let running = false;
  let prompting = false;
  let keepalive: ReturnType<typeof setInterval> | undefined;
  // Reports go out one at a time, in order: two concurrent connections could
  // land `idle` before the `working` that preceded it.
  let chain: Promise<void> = Promise.resolve();
  let pending = 0;

  function deliver(line: string): Promise<void> {
    return new Promise((resolve) => {
      let done = false;
      const finish = () => {
        if (!done) {
          done = true;
          clearTimeout(timer);
          socket.destroy();
          resolve();
        }
      };
      const socket = createConnection(SOCKET);
      const timer = setTimeout(finish, SEND_TIMEOUT_MS);
      socket.on("error", finish);
      socket.on("close", finish);
      socket.on("data", finish);
      socket.on("connect", () => socket.write(line));
    });
  }

  function send(op: string, payload: Record<string, unknown>): void {
    if (pending >= MAX_PENDING) {
      return;
    }
    pending += 1;
    const line = `${JSON.stringify({ service: "sessions", op, payload })}\n`;
    chain = chain
      .then(() => deliver(line))
      .catch(() => undefined)
      .finally(() => {
        pending -= 1;
      });
  }

  function noteContext(ctx: Any): void {
    try {
      const id = ctx?.model?.id;
      if (session && typeof id === "string" && id) {
        session.model = id;
      }
    } catch {
      // Best-effort metadata only.
    }
  }

  function report(next: State, force = false): void {
    if (!session || (!force && next === state)) {
      return;
    }
    state = next;
    send("observe", {
      session_id: session.id,
      cwd: session.cwd,
      transcript_path: session.file,
      model: session.model,
      agent: "pi",
      event: { stream_state: next },
    });
  }

  /** Wraps a handler so nothing it does can throw into pi. */
  function on(event: string, handler: (event: Any, ctx: Any) => void): void {
    pi.on(event, (event: Any, ctx: Any) => {
      try {
        noteContext(ctx);
        handler(event, ctx);
      } catch {
        // Fail open: the feed must never break a pi session.
      }
    });
  }

  function stopKeepalive(): void {
    if (keepalive !== undefined) {
      clearInterval(keepalive);
      keepalive = undefined;
    }
  }

  on("session_start", (_event, ctx) => {
    const id = ctx.sessionManager?.getSessionId?.();
    if (typeof id !== "string" || !id) {
      return;
    }
    const file = ctx.sessionManager?.getSessionFile?.();
    session = {
      id,
      cwd: typeof ctx.cwd === "string" ? ctx.cwd : undefined,
      file: typeof file === "string" ? file : undefined,
    };
    noteContext(ctx);
    running = false;
    prompting = false;
    // The session announced itself but has not been prompted yet — pi's chat
    // input is already live at this point, so this reads as idle rather than
    // busy (mirrors the stream wrapper's `init` handling for Claude, ADR-0057;
    // reporting `starting` here left every session showing as busy from launch
    // until the first prompt completed, since `starting` buckets as working
    // everywhere it is rendered).
    report("idle", true);
    stopKeepalive();
    keepalive = setInterval(() => report(state, true), KEEPALIVE_MS);
    keepalive.unref?.();
  });

  const busy = () => {
    running = true;
    if (!prompting) {
      report("working");
    }
  };
  on("before_agent_start", busy);
  on("agent_start", busy);
  on("turn_start", busy);
  on("tool_execution_start", busy);

  on("agent_settled", () => {
    running = false;
    if (!prompting) {
      report("idle");
    }
  });

  // pi has no per-tool permission prompt (its approval model is project trust),
  // so every blocking UI prompt reads as waiting for input.
  on("ui_prompt_start", () => {
    prompting = true;
    report("waiting_for_input");
  });
  on("ui_prompt_end", () => {
    prompting = false;
    report(running ? "working" : "idle");
  });

  pi.on("session_shutdown", (event: Any) => {
    try {
      stopKeepalive();
      if (session) {
        const reason = typeof event?.reason === "string" ? event.reason : undefined;
        send("end", { session_id: session.id, reason });
        session = undefined;
      }
    } catch {
      return undefined;
    }
    // Let the `end` report leave before pi exits, but never hold pi up for long.
    return Promise.race([
      chain,
      new Promise<void>((resolve) => setTimeout(resolve, SHUTDOWN_FLUSH_MS).unref?.()),
    ]);
  });
}
